const cards = [
    {value: 'cat.png',
    index: '',
    alt:'cat playing',
    faceUp: false,},
    {value: 'walking-dog.png',
    index: '',
    alt:'woman walking a dog',
    faceUp: false,},
    {value: 'cat-on-the-couch.png',
    index: '',
    alt:'man sitting on the couch with a cat',
    faceUp: false,},
    {value: 'dog-eating.png',
    index: '',
    alt:'a dog eating',
    faceUp: false,},
    {value: 'heart.png',
    index: '',
    alt:'heart',
    faceUp: false,},
    {value: 'dog.svg',
    index: '',
    alt:'a dog running',
    faceUp: false,},
    {value: 'cat.png',
    index: '',
    alt:'cat playing',
    faceUp: false,},
    {value: 'walking-dog.png',
    index: '',
    alt:'woman walking a dog',
    faceUp: false,},
    {value: 'cat-on-the-couch.png',
    index: '',
    alt:'man sitting on the couch with a cat',
    faceUp: false,},
    {value: 'dog-eating.png',
    index: '',
    alt:'a dog eating',
    faceUp: false,},
    {value: 'heart.png',
    index: '',
    alt:'heart',
    faceUp: false,},
    {value: 'dog.svg',
    index: '',
    alt:'a dog running',
    faceUp: false,}
]

export default cards;