const cards = [
    {value: 'cat.png',
    index: '',
    faceUp: false,},
    {value: 'walking-dog.png',
    index: '',
    faceUp: false,},
    {value: 'cat-on-the-couch.png',
    index: '',
    faceUp: false,},
    {value: 'dog-eating.png',
    index: '',
    faceUp: false,},
    {value: 'heart.png',
    index: '',
    faceUp: false,},
    {value: 'dog.svg',
    index: '',
    faceUp: false,},
    {value: 'cat.png',
    index: '',
    faceUp: false,},
    {value: 'walking-dog.png',
    index: '',
    faceUp: false,},
    {value: 'cat-on-the-couch.png',
    index: '',
    faceUp: false,},
    {value: 'dog-eating.png',
    index: '',
    faceUp: false,},
    {value: 'heart.png',
    index: '',
    faceUp: false,},
    {value: 'dog.svg',
    index: '',
    faceUp: false,}
]

export default cards;