const cards = [
    {value: 'A',
    index: '',
    faceUp: false,},
    {value: 'B',
    index: '',
    faceUp: false,},
    {value: 'C',
    index: '',
    faceUp: false,},
    {value: 'D',
    index: '',
    faceUp: false,},
    {value: 'E',
    index: '',
    faceUp: false,},
    {value: 'F',
    index: '',
    faceUp: false,},
    {value: 'A',
    index: '',
    faceUp: false,},
    {value: 'B',
    index: '',
    faceUp: false,},
    {value: 'C',
    index: '',
    faceUp: false,},
    {value: 'D',
    index: '',
    faceUp: false,},
    {value: 'E',
    index: '',
    faceUp: false,},
    {value: 'F',
    index: '',
    faceUp: false,}
]

export default cards;